version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # build site!
      - run: yarn build

  test:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test --coverage --coverageDirectory=coverage

      - codecov/upload:
          token: $CODECOV_TOKEN
          file: ~/repo/coverage/coverage-final.json

  lint:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # check linter!
      - run: yarn lint

  deploy:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: 
          name: Install and configure github and gh-pages
          command: |
            yarn global add gh-pages@2.0.1
            ls
            cd ~/repo
            git config user.email "alexbarkin+ci-build@rogers.com"
            git config user.name "alexbarkin+ci-build"
      - add_ssh_keys:
          fingerprints:
            - a4:8a:fe:af:db:04:27:4c:c8:36:37:49:5f:f7:21:3e

      - run: yarn deploy

workflows:
  build_test_lint:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - build
      - lint
      - deploy:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: 
                - Gatsby-Dev
